### ISSUE TITLE
Restore Snakenet Finality

### ISSUE THREAD

**Issue by lumir-mrkva** [galacticcouncil/HydraDX-node#237]
- [x] update to latest substrate #222 
- [x] add election failback #221
- [x] fix node justification import #225   
- [x] deploy runtime upgrade
- [x] try restoring finality by triggering another stalled event

in case this fails, we have 2 options
- [x] sync 2/3 validators to *960 finality block and start finalizing from there: https://github.com/galacticcouncil/HydraDX-node/pull/225#issuecomment-827805887
- [x] gen 3 

- [x] integrate batch pallet #218
- [x] send validator/nominator rewards in batch
