### ISSUE TITLE
Prepare genesis 3

### ISSUE THREAD

**Issue by jak-pan** [galacticcouncil/HydraDX-node#243]
This time we stumbled upon a bug in the finality tracker...

PHASE 1:
- [x] upgrade to v11 @jak-pan 
- [x] Prepare re-geneis scraping script @jak-pan 
- [x] Make sure session keys are migrated
- [x] Update protocolId
- [x] Store genesis and last block of the gen2 in the gen3 #192 
- [x] Update chain_spec and node to connect to the new chain
- [x] Soft pause gen1 #209 

PHASE 2:
- [x] Start gen3
- [x] Update Polkadot-js/common #195

PHASE 3: 
- [x] Kill the gen2 paritytech/substrate#7458
- [x] Release ~7.0.0~ 8.0.0
- [x] Coordinate upgrade with validators
