### ISSUE TITLE
Storage migration script

### ISSUE THREAD

**Issue by jak-pan** [galacticcouncil/HydraDX-node#334]
Re-genesis should be done via sudo batch transaction script called after we are onboarded as a parachain. We should check if we should do the data migration prior to runtime upgrade or after

Relevant information
- https://hydradx.substack.com/p/the-3x
- https://github.com/galacticcouncil/fork-off-hydra/blob/7149a33a6f08ed06638c2de883cd269ee6ee6ed5/index.js#L39
- https://www.shawntabrizi.com/substrate/transparent-keys-in-substrate/

Sub tasks
- [x] check if we need to call setData before, after or both before and after the upgrade to full HydraDX parachain from shell
- [x] check latest migration code of Centrifuge
- [x] look into all the migrations that happened since the last upgrade and make sure we migrate the data (https://github.com/galacticcouncil/HydraDX-node/issues/357)
- [x] #359 
- [x] #360 
- [x] validate complete migration by test run and manual data validation
